using System;
using System.Collections;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;
using System.Windows.Data;

namespace AssemblyPropertiesViewer.Controls
{
    public class DynamicDictionaryBasedDataGrid : DataGrid
    {
        protected override void OnItemsSourceChanged(IEnumerable oldValue, IEnumerable newValue)
        {
            base.OnItemsSourceChanged(oldValue, newValue);
            
        }

        protected override void OnAutoGeneratedColumns(EventArgs e)
        {
            //base.OnAutoGeneratedColumns(e);

            if (!this.AutoGenerateColumns)
                return;

            this.Columns.Clear();

            ExpandoObject firstRow = (this.ItemsSource as IEnumerable<dynamic>)?.FirstOrDefault();

            List<string> propertyNames = (firstRow as IDictionary<string, object>)?.Keys.ToList();

            if (propertyNames == null)
                return;

            foreach (var propName in propertyNames)
            {
                this.Columns.Add(new DataGridTextColumn()
                {
                    Header = propName,
                    Binding = new Binding(propName)
                });
            }
        }
    }
}
